import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar configuration for the Physical AI & Humanoid Robotics textbook
  textbookSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Robotic Nervous System (ROS 2)',
      items: [
        'robotic-nervous-system/chapter-1-introduction-to-physical-ai',
        'robotic-nervous-system/chapter-2-sensor-systems',
        'robotic-nervous-system/chapter-3-actuator-systems',
        'robotic-nervous-system/chapter-4-communication-protocols',
        'robotic-nervous-system/chapter-5-control-architectures',
        'robotic-nervous-system/chapter-6-ros-2-ecosystem'
      ],
    },
    {
      type: 'category',
      label: 'Digital Twin (Gazebo & Unity)',
      items: [
        'digital-twin/chapter-1-simulation-fundamentals',
        'digital-twin/chapter-2-physics-modeling',
        'digital-twin/chapter-3-gazebo-framework',
        'digital-twin/chapter-4-unity-integration',
        'digital-twin/chapter-5-digital-twin-applications',
        'digital-twin/chapter-6-simulation-best-practices'
      ],
    },
    {
      type: 'category',
      label: 'AI-Robot Brain (NVIDIA Isaac)',
      items: [
        'ai-robot-brain/chapter-1-ai-computing-platforms',
        'ai-robot-brain/chapter-2-perception-systems',
        'ai-robot-brain/chapter-3-planning-navigation',
        'ai-robot-brain/chapter-4-control-systems',
        'ai-robot-brain/chapter-5-deep-learning-integration',
        'ai-robot-brain/chapter-6-nvidia-isaac-applications'
      ],
    },
    {
      type: 'category',
      label: 'Vision-Language-Action (VLA)',
      items: [
        'vla-systems/chapter-1-multimodal-perception',
        'vla-systems/chapter-2-visual-processing',
        'vla-systems/chapter-3-language-understanding',
        'vla-systems/chapter-4-action-generation',
        'vla-systems/chapter-5-integration-architectures',
        'vla-systems/chapter-6-vla-applications'
      ],
    },
    {
      type: 'category',
      label: 'Humanoid Mechanics',
      items: [
        'humanoid-mechanics/chapter-1-humanoid-design-principles',
        'humanoid-mechanics/chapter-2-kinematics-dynamics',
        'humanoid-mechanics/chapter-3-mechanical-components',
        'humanoid-mechanics/chapter-4-locomotion-systems',
        'humanoid-mechanics/chapter-5-balance-stability',
        'humanoid-mechanics/chapter-6-mechanical-safety'
      ],
    },
    {
      type: 'category',
      label: 'Perception & SLAM',
      items: [
        'perception-slam/chapter-1-sensor-fusion',
        'perception-slam/chapter-2-mapping-techniques',
        'perception-slam/chapter-3-localization-systems',
        'perception-slam/chapter-4-slam-algorithms',
        'perception-slam/chapter-5-3d-reconstruction',
        'perception-slam/chapter-6-environmental-understanding'
      ],
    },
    {
      type: 'category',
      label: 'Conversational Robotics',
      items: [
        'conversational-robotics/chapter-1-human-robot-interaction',
        'conversational-robotics/chapter-2-speech-recognition',
        'conversational-robotics/chapter-3-natural-language-processing',
        'conversational-robotics/chapter-4-dialogue-management',
        'conversational-robotics/chapter-5-social-robotics',
        'conversational-robotics/chapter-6-conversational-ai-applications'
      ],
    },
    {
      type: 'category',
      label: 'Capstone: Autonomous Humanoid',
      items: [
        'capstone/chapter-1-system-integration',
        'capstone/chapter-2-autonomous-behaviors',
        'capstone/chapter-3-task-planning',
        'capstone/chapter-4-safety-ethics',
        'capstone/chapter-5-performance-optimization',
        'capstone/chapter-6-future-directions'
      ],
    },
    {
      type: 'category',
      label: 'RAG Chatbot Integration',
      items: [
        'intro' // Placeholder - will be updated later
      ],
    },
    {
      type: 'category',
      label: 'Authentication & Personalization',
      items: [
        'intro' // Placeholder - will be updated later
      ],
    },
    {
      type: 'category',
      label: 'Hardware & Lab Architecture',
      items: [
        'intro' // Placeholder - will be updated later
      ],
    }
  ],
};

export default sidebars;
